use std::process::Stdio;

use tauri::{AppHandle, Emitter, Runtime, State};
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};
use tokio::process::Command as TokioCommand;
use tokio::sync::oneshot;

use crate::core::state::AppState;

/// Payload emitted to the frontend for each JSONL line produced by `codex exec`.
/// The `session_id` lets the frontend route events to the correct agent session
/// when multiple turns are in flight (though only one runs at a time today).
#[derive(Debug, Clone, serde::Serialize)]
struct CodexAgentEvent {
    event: serde_json::Value,
    session_id: String,
}

/// Spawn a Codex agent turn and stream the resulting JSONL events back to the
/// frontend via the `codex://agent-event` Tauri event channel.
///
/// The turn is one call to `codex exec --experimental-json`.  For multi-turn
/// conversations, pass the `thread_id` returned by the previous call; Codex
/// will resume that session via `codex exec --experimental-json resume <id>`.
///
/// Returns the thread ID assigned by Codex (stable across turns).
#[tauri::command]
pub async fn codex_run_turn<R: Runtime>(
    app: AppHandle<R>,
    state: State<'_, AppState>,
    // Opaque ID generated by the frontend to disambiguate concurrent calls.
    session_id: String,
    prompt: String,
    // Omit or pass null for the first turn in a new session.
    thread_id: Option<String>,
    // Directory Codex should treat as the project root.  Defaults to $HOME.
    working_dir: Option<String>,
    // Custom path to the `codex` binary (None → search PATH).
    binary_path: Option<String>,
    // Custom path to config.toml; its parent dir is passed as CODEX_HOME.
    config_path: Option<String>,
) -> Result<String, String> {
    let mut args = vec!["exec".to_string(), "--experimental-json".to_string()];

    if let Some(dir) = &working_dir {
        if !dir.trim().is_empty() {
            args.push("--cd".to_string());
            args.push(dir.clone());
        }
    }

    // A non-empty thread_id resumes an existing conversation.
    let current_thread_id = thread_id.unwrap_or_default();
    if !current_thread_id.trim().is_empty() {
        args.push("resume".to_string());
        args.push(current_thread_id.clone());
    }

    // Resolve the binary to invoke.
    let binary = binary_path
        .as_deref()
        .filter(|s| !s.trim().is_empty())
        .unwrap_or("codex");

    // Derive CODEX_HOME from the config file path when provided.
    let codex_home_override: Option<std::path::PathBuf> = config_path
        .as_deref()
        .filter(|s| !s.trim().is_empty())
        .and_then(|p| std::path::Path::new(p).parent().map(|d| d.to_path_buf()));

    // Set up a cancellation channel so `codex_stop_turn` can abort the process.
    let (cancel_tx, cancel_rx) = oneshot::channel::<()>();
    {
        let mut guard = state.codex_cancel.lock().await;
        *guard = Some(cancel_tx);
    }

    let mut cmd = TokioCommand::new(binary);
    cmd.args(&args)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    if let Some(home) = codex_home_override {
        cmd.env("CODEX_HOME", home);
    }
    let mut child = cmd
        .spawn()
        .map_err(|e| {
            format!(
                "Failed to spawn codex: {e}. Is the Codex CLI installed and on PATH?"
            )
        })?;

    // Write the prompt to stdin and close the pipe so Codex starts processing.
    if let Some(mut stdin) = child.stdin.take() {
        stdin
            .write_all(prompt.as_bytes())
            .await
            .map_err(|e| e.to_string())?;
        // stdin drop closes the write end of the pipe.
    }

    let stdout = child
        .stdout
        .take()
        .ok_or("codex process produced no stdout")?;

    let reader = BufReader::new(stdout);
    let mut lines = reader.lines();
    let mut resolved_thread_id = current_thread_id.clone();

    // Emit each JSONL line as a Tauri event, or bail early if cancelled.
    let read_result: Result<String, String> = tokio::select! {
        biased;

        // Cancellation path: kill the child and emit a synthetic event.
        _ = cancel_rx => {
            child.kill().await.ok();
            let _ = app.emit(
                "codex://agent-event",
                &CodexAgentEvent {
                    event: serde_json::json!({ "type": "turn.cancelled" }),
                    session_id: session_id.clone(),
                },
            );
            Ok(resolved_thread_id.clone())
        }

        // Normal path: drain stdout until EOF.
        result = async {
            loop {
                match lines.next_line().await {
                    Ok(Some(line)) => {
                        if line.is_empty() {
                            continue;
                        }
                        match serde_json::from_str::<serde_json::Value>(&line) {
                            Ok(event) => {
                                // Capture the thread ID from the first event.
                                if event["type"].as_str() == Some("thread.started") {
                                    if let Some(tid) = event["thread_id"].as_str() {
                                        resolved_thread_id = tid.to_string();
                                    }
                                }
                                let _ = app.emit(
                                    "codex://agent-event",
                                    &CodexAgentEvent {
                                        event,
                                        session_id: session_id.clone(),
                                    },
                                );
                            }
                            Err(e) => {
                                // Forward malformed lines as error events so the
                                // frontend can surface them rather than silently drop.
                                let _ = app.emit(
                                    "codex://agent-event",
                                    &CodexAgentEvent {
                                        event: serde_json::json!({
                                            "type": "error",
                                            "message": format!("Parse error: {e} — raw: {line}"),
                                        }),
                                        session_id: session_id.clone(),
                                    },
                                );
                            }
                        }
                    }
                    Ok(None) => break, // EOF: Codex finished this turn.
                    Err(e) => return Err(e.to_string()),
                }
            }
            Ok::<(), String>(())
        } => {
            result?;
            Ok(resolved_thread_id.clone())
        }
    };

    // Best-effort wait so we don't leave zombie processes around.
    child.wait().await.ok();

    // Release the cancel sender now that the process is done.
    {
        let mut guard = state.codex_cancel.lock().await;
        *guard = None;
    }

    read_result
}

/// Signal the currently-running `codex_run_turn` to terminate early.
#[tauri::command]
pub async fn codex_stop_turn(state: State<'_, AppState>) -> Result<(), String> {
    let mut guard = state.codex_cancel.lock().await;
    if let Some(tx) = guard.take() {
        // Ignore send errors — the receiver may already be gone if the turn
        // finished naturally between the UI click and this handler running.
        tx.send(()).ok();
    }
    Ok(())
}
